# Generated by Django 2.1.7 on 2019-06-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainname',
            name='beian',
            field=models.IntegerField(blank=True, null=True, verbose_name='备案状态'),
        ),
    ]
