# Generated by Django 2.1.7 on 2019-06-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_name', '0002_domainname_beian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='beian',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '未备案'), (3, '掉备案')], null=True, verbose_name='备案状态'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='domain_status',
            field=models.IntegerField(default=3, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='registrar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='域名注册商'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='registration_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='domainnameaccount',
            name='resolver',
            field=models.CharField(choices=[('aliyun', '阿里云'), ('dnspod', 'DNSPod')], max_length=50, verbose_name='所属域名解析商'),
        ),
    ]
