# Generated by Django 2.1.7 on 2019-07-03 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0026_node_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeConfigRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=128, verbose_name='域名')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('proxy_port', models.IntegerField(verbose_name='代理端口')),
                ('comment', models.TextField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '节点配置记录',
                'db_table': 'config_node_records',
            },
        ),
        migrations.CreateModel(
            name='PlatformNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('public_node_port', models.ImageField(default=10125, upload_to='', verbose_name='公共节点端口')),
                ('private_node_port', models.ImageField(default=10125, upload_to='', verbose_name='私有节点端口')),
                ('comment', models.TextField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Node', verbose_name='项目')),
                ('private_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_node_asset', to='assets.Asset', verbose_name='私有节点')),
                ('public_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_node_asset', to='assets.Asset', verbose_name='公共节点')),
            ],
            options={
                'verbose_name': '平台节点',
                'db_table': 'config_node_to_platform',
            },
        ),
        migrations.AddField(
            model_name='nodeconfigrecords',
            name='platfrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PlatformNode', verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='nodeconfigrecords',
            name='proxy_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset', verbose_name='代理IP'),
        ),
    ]
