# Generated by Django 2.1.7 on 2019-07-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_auto_20190221_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='别名'),
        ),
    ]
